# Sesión 1 — Ingesta y Arquitectura de Tablas
**FLACSO Ecuador — Estructura Social y Espacial de los Datos y su Arquitectura**  
Docente: Fausto Jácome Pérez

---

## Antes de empezar

Instala las dependencias si aún no lo has hecho:

```bash
pip install -r requirements.txt
```

Descarga los datos de la ENDI desde los links en `Materiales/Insumos/ENDI/links_descarga.txt`  
y colócalos en `Materiales/Insumos/ENDI/BDD_ENDI_R2_rds/`.

## 1. Carga de datos

La ENDI se distribuye en formato `.rds` (nativo de R).
Para leerlo desde Python usamos `pyreadr`, que devuelve un DataFrame de pandas.
Luego lo convertimos a Polars, que es la librería principal del curso.

In [10]:
import pyreadr
import polars as pl
import pandas as pd

ruta = "../../Materiales/Insumos/ENDI/BDD_ENDI_R2_rds/BDD_ENDI_R2_f1_personas.rds"

df = pl.from_pandas(
    pyreadr.read_r(ruta)[None]
)

print("Si hay un check verde aquí abajo a la izquierda, todo ok")

Si hay un check verde aquí abajo a la izquierda, todo ok

## 2. Exploración inicial

### 2.1 Forma de la tabla

In [5]:
# Número de filas y columnas
print(df.shape)
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

(93242, 124)
Filas: 93242
Columnas: 124

### 2.2 Esquema: nombres de columnas y tipos

In [8]:
# Schema completo
print(df.schema)

Schema({'id_upm': String, 'id_viv': String, 'id_hogar': String, 'id_per': String, 'id_mef': String, 'fecha_anio': String, 'fecha_mes': String, 'fecha_dia': String, 'fexp': Float64, 'estrato': String, 'area': Float64, 'region': Float64, 'prov': Float64, 'parr_pri': Float64, 'etnia': Float64, 'persona': String, 'altitud': Int32, 'edaddias': Float64, 'grupo_edad_nin': Float64, 'nivins_mef': Float64, 'f1_s1_1': Int32, 'f1_s1_2': Int32, 'f1_s1_3_1': Int32, 'f1_s1_4_1': Int32, 'f1_s1_4_2': Int32, 'f1_s1_4_3': Int32, 'f1_s1_5': Int32, 'f1_s1_6': Int32, 'f1_s1_6_2': Int64, 'f1_s1_7_a': Int64, 'f1_s1_7_b': Int64, 'f1_s1_7_c': Int64, 'f1_s1_7_d': Int64, 'f1_s1_7_e': Int64, 'f1_s1_7_f': Int64, 'f1_s1_8': Int32, 'f1_s1_9': Int64, 'f1_s1_10': Int32, 'f1_s1_11': Int32, 'f1_s1_11_1': Int64, 'f1_s1_12': Int32, 'f1_s1_12_1': Int64, 'f1_s1_13': Int32, 'f1_s1_14': Int64, 'f1_s1_15_1': Int32, 'f1_s1_15_2': Float64, 'f1_s1_16': Int64, 'f1_s1_17': Int64, 'f1_s1_18': Int64, 'f1_s2_1': Int64, 'f1_s2_2': Int64, 'f1_s2_3': Int64, 'f1_s2_4': Int64, 'f1_s2_5': Int64, 'f1_s2_6': Int64, 'f1_s2_7': Int64, 'f1_s2_8': Int64, 'f1_s2_9': Float64, 'f1_s2_10_1': Int64, 'f1_s2_10_2': Int64, 'f1_s2_11': Float64, 'f1_s2_12': Int64, 'f1_s2_13': Int64, 'f1_s2_14_1': Int64, 'f1_s2_14_2': Int64, 'f1_s2_15': Int64, 'f1_s2_16_1': Int64, 'f1_s2_16_2': Int64, 'f1_s2_17_1': Int64, 'f1_s2_17_2': Int64, 'f1_s2_18_1': Int64, 'f1_s2_18_2': Int64, 'f1_s2_19_1': Int64, 'f1_s2_19_2': Int64, 'f1_s2_20_1': Int64, 'f1_s2_20_2': Int64, 'f1_s2_21': Int64, 'f1_s2_22': Int64, 'f1_s2_23': Int64, 'f1_s2_24': Int64, 'f1_s2_25': Int64, 'f1_s2_26': Int64, 'f1_s5_1': Int64, 'f1_s5_2_1': Int64, 'f1_s5_2_2': Int64, 'f1_s5_2_3': Int64, 'f1_s5_3_1': Int64, 'f1_s5_3_2': Int64, 'f1_s5_3_3': Int64, 'f1_s5_4_1': Float64, 'f1_s5_4_2': Float64, 'f1_s5_4_3': Float64, 'f1_s5_5_1': Float64, 'f1_s5_5_2': Float64, 'f1_s5_5_3': Float64, 'f1_s5_6_1': Float64, 'f1_s5_6_2': Float64, 'f1_s5_6_3': Float64, 'f1_s5_7': Int64, 'f1_s6_1': Int64, 'f1_s6_2': Int64, 'f1_s6_3': Float64, 'f1_s6_4_1': Int64, 'f1_s6_4_2': Int64, 'f1_s6_5_1': Int64, 'f1_s6_5_2': Int64, 'f1_s6_5_3': Int64, 'f1_s6_6': Int64, 'quintil': Float64, 'pobreza': Float64, 'nbi_1': Float64, 'dcronica_2': Float64, 'dglobal_2': Float64, 'daguda_2': Float64, 'dcronica': Float64, 'dglobal': Float64, 'daguda': Float64, 'dcronica2_5': Float64, 'dglobal2_5': Float64, 'daguda2_5': Float64, 'ane6_59': Float64, 'ane6_59_new': Float64, 'ane6_23': Float64, 'ane6_23_new': Float64})

In [ ]:
# Como tabla legible (uso pandas porque Polars no se ve y no es una tabla de procesamiento)
pd.DataFrame({
    "columna": df.columns,
    "tipo": [str(t) for t in df.dtypes]
})

         columna     tipo
0         id_upm   String
1         id_viv   String
2       id_hogar   String
3         id_per   String
4         id_mef   String
..           ...      ...
119    daguda2_5  Float64
120      ane6_59  Float64
121  ane6_59_new  Float64
122      ane6_23  Float64
123  ane6_23_new  Float64

[124 rows x 2 columns]

### 2.3 Primeras filas

In [12]:
df.head(5)

shape: (5, 124)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬───────────┬─────────┬───────────┐
│ id_upm     ┆ id_viv     ┆ id_hogar   ┆ id_per    ┆ … ┆ ane6_59 ┆ ane6_59_n ┆ ane6_23 ┆ ane6_23_n │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---     ┆ ew        ┆ ---     ┆ ew        │
│ str        ┆ str        ┆ str        ┆ str       ┆   ┆ f64     ┆ ---       ┆ f64     ┆ ---       │
│            ┆            ┆            ┆           ┆   ┆         ┆ f64       ┆         ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═════════╪═══════════╡
│ 0101500088 ┆ 0101500088 ┆ 0101500088 ┆ 010150008 ┆ … ┆ null    ┆ null      ┆ null    ┆ null      │
│            ┆ 01         ┆ 0101       ┆ 8010101   ┆   ┆         ┆           ┆         ┆           │
│ 0101500088 ┆ 0101500088 ┆ 0101500088 ┆ 010150008 ┆ … ┆ null    ┆ null      ┆ null    ┆ null      │
│            ┆ 01         ┆ 0101       ┆ 8010102   ┆   ┆         ┆           ┆         ┆           │
│ 0101500088 ┆ 0101500088 ┆ 0101500088 ┆ 010150008 ┆ … ┆ null    ┆ null      ┆ null    ┆ null      │
│            ┆ 01         ┆ 0101       ┆ 8010103   ┆   ┆         ┆           ┆         ┆           │
│ 0101500088 ┆ 0101500088 ┆ 0101500088 ┆ 010150008 ┆ … ┆ null    ┆ null      ┆ null    ┆ null      │
│            ┆ 01         ┆ 0101       ┆ 8010104   ┆   ┆         ┆           ┆         ┆           │
│ 0101500088 ┆ 0101500088 ┆ 0101500088 ┆ 010150008 ┆ … ┆ 4.0     ┆ 0.0       ┆ null    ┆ null      │
│            ┆ 01         ┆ 0101       ┆ 8010105   ┆   ┆         ┆           ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴───────────┴─────────┴───────────┘

## 3. Variables numéricas

`describe()` devuelve: `count`, `null_count`, `mean`, `std`, `min`, `25%`, `50%`, `75%`, `max`

In [13]:
# Resumen de todas las variables
df.describe()

shape: (9, 125)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬──────────┬───────────┐
│ statistic  ┆ id_upm    ┆ id_viv    ┆ id_hogar  ┆ … ┆ ane6_59  ┆ ane6_59_n ┆ ane6_23  ┆ ane6_23_n │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ew        ┆ ---      ┆ ew        │
│ str        ┆ str       ┆ str       ┆ str       ┆   ┆ f64      ┆ ---       ┆ f64      ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆          ┆ f64       ┆          ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪══════════╪═══════════╡
│ count      ┆ 93242     ┆ 93242     ┆ 93242     ┆ … ┆ 20222.0  ┆ 20222.0   ┆ 6392.0   ┆ 6392.0    │
│ null_count ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 73020.0  ┆ 73020.0   ┆ 86850.0  ┆ 86850.0   │
│ mean       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.559341 ┆ 0.326427  ┆ 3.473404 ┆ 0.370307  │
│ std        ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.693256 ┆ 0.468917  ┆ 0.758561 ┆ 0.482925  │
│ min        ┆ 010150000 ┆ 010150000 ┆ 010150000 ┆ … ┆ 1.0      ┆ 0.0       ┆ 1.0      ┆ 0.0       │
│            ┆ 7         ┆ 701       ┆ 70101     ┆   ┆          ┆           ┆          ┆           │
│ 25%        ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.0      ┆ 0.0       ┆ 3.0      ┆ 0.0       │
│ 50%        ┆ null      ┆ null      ┆ null      ┆ … ┆ 4.0      ┆ 0.0       ┆ 4.0      ┆ 0.0       │
│ 75%        ┆ null      ┆ null      ┆ null      ┆ … ┆ 4.0      ┆ 1.0       ┆ 4.0      ┆ 1.0       │
│ max        ┆ 240352003 ┆ 240352003 ┆ 240352003 ┆ … ┆ 4.0      ┆ 1.0       ┆ 4.0      ┆ 1.0       │
│            ┆ 1         ┆ 108       ┆ 10801     ┆   ┆          ┆           ┆          ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴──────────┴───────────┘

In [17]:
# Solo columnas numéricas
df.select(pl.selectors.numeric()).describe()

shape: (9, 115)
┌────────────┬───────────┬──────────┬──────────┬───┬──────────┬────────────┬──────────┬────────────┐
│ statistic  ┆ fexp      ┆ area     ┆ region   ┆ … ┆ ane6_59  ┆ ane6_59_ne ┆ ane6_23  ┆ ane6_23_ne │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ ---      ┆ w          ┆ ---      ┆ w          │
│ str        ┆ f64       ┆ f64      ┆ f64      ┆   ┆ f64      ┆ ---        ┆ f64      ┆ ---        │
│            ┆           ┆          ┆          ┆   ┆          ┆ f64        ┆          ┆ f64        │
╞════════════╪═══════════╪══════════╪══════════╪═══╪══════════╪════════════╪══════════╪════════════╡
│ count      ┆ 93242.0   ┆ 93242.0  ┆ 93242.0  ┆ … ┆ 20222.0  ┆ 20222.0    ┆ 6392.0   ┆ 6392.0     │
│ null_count ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ … ┆ 73020.0  ┆ 73020.0    ┆ 86850.0  ┆ 86850.0    │
│ mean       ┆ 1.0       ┆ 1.395401 ┆ 1.704618 ┆ … ┆ 3.559341 ┆ 0.326427   ┆ 3.473404 ┆ 0.370307   │
│ std        ┆ 1.311398  ┆ 0.488939 ┆ 0.781146 ┆ … ┆ 0.693256 ┆ 0.468917   ┆ 0.758561 ┆ 0.482925   │
│ min        ┆ 0.030432  ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 0.0        ┆ 1.0      ┆ 0.0        │
│ 25%        ┆ 0.326114  ┆ 1.0      ┆ 1.0      ┆ … ┆ 3.0      ┆ 0.0        ┆ 3.0      ┆ 0.0        │
│ 50%        ┆ 0.58146   ┆ 1.0      ┆ 2.0      ┆ … ┆ 4.0      ┆ 0.0        ┆ 4.0      ┆ 0.0        │
│ 75%        ┆ 1.097537  ┆ 2.0      ┆ 2.0      ┆ … ┆ 4.0      ┆ 1.0        ┆ 4.0      ┆ 1.0        │
│ max        ┆ 19.379266 ┆ 2.0      ┆ 3.0      ┆ … ┆ 4.0      ┆ 1.0        ┆ 4.0      ┆ 1.0        │
└────────────┴───────────┴──────────┴──────────┴───┴──────────┴────────────┴──────────┴────────────┘

## 4. Variables categóricas

In [27]:
# Categorías únicas y conteo para variables clave

for col in ["area", "region"]:
    print(df[col].value_counts(sort=True))

shape: (2, 2)
┌──────┬───────┐
│ area ┆ count │
│ ---  ┆ ---   │
│ f64  ┆ u32   │
╞══════╪═══════╡
│ 1.0  ┆ 56374 │
│ 2.0  ┆ 36868 │
└──────┴───────┘
shape: (3, 2)
┌────────┬───────┐
│ region ┆ count │
│ ---    ┆ ---   │
│ f64    ┆ u32   │
╞════════╪═══════╡
│ 1.0    ┆ 46286 │
│ 2.0    ┆ 28212 │
│ 3.0    ┆ 18744 │
└────────┴───────┘

## 5. Datos perdidos

En la ENDI los missings no son siempre aleatorios — pueden indicar que un registro no aplica a cierta sección del formulario.

In [31]:
print(df.null_count())

shape: (1, 124)
┌────────┬────────┬──────────┬────────┬───┬─────────┬─────────────┬─────────┬─────────────┐
│ id_upm ┆ id_viv ┆ id_hogar ┆ id_per ┆ … ┆ ane6_59 ┆ ane6_59_new ┆ ane6_23 ┆ ane6_23_new │
│ ---    ┆ ---    ┆ ---      ┆ ---    ┆   ┆ ---     ┆ ---         ┆ ---     ┆ ---         │
│ u32    ┆ u32    ┆ u32      ┆ u32    ┆   ┆ u32     ┆ u32         ┆ u32     ┆ u32         │
╞════════╪════════╪══════════╪════════╪═══╪═════════╪═════════════╪═════════╪═════════════╡
│ 0      ┆ 0      ┆ 0        ┆ 0      ┆ … ┆ 73020   ┆ 73020       ┆ 86850   ┆ 86850       │
└────────┴────────┴──────────┴────────┴───┴─────────┴─────────────┴─────────┴─────────────┘

In [34]:
# Conteo de nulos por columna
nulos = df.null_count().transpose(
    include_header=True,
    column_names=["n_nulos"]
).with_columns(
    (pl.col("n_nulos") / df.shape[0]).alias("pct_nulo")
    ).sort("pct_nulo", descending=True)

# Mostrar solo columnas con al menos un nulo
nulos.filter(pl.col("n_nulos") > 0).to_pandas()

        column  n_nulos  pct_nulo
0    f1_s5_5_3    93239  0.999968
1    f1_s5_6_3    93210  0.999657
2    f1_s5_4_3    93185  0.999389
3     f1_s2_24    93105  0.998531
4   f1_s2_17_2    92747  0.994691
..         ...      ...       ...
87   f1_s1_7_e    23187  0.248675
88   f1_s1_7_f    23187  0.248675
89     quintil      572  0.006135
90     pobreza      563  0.006038
91    edaddias       21  0.000225

[92 rows x 3 columns]

## 6. Preguntas para reflexionar

1. ¿Qué tipo de dato tiene `fexp`? ¿Tiene sentido ese tipo para un factor de expansión?
2. ¿Qué tipo de dato tiene `prov` (código de provincia)? ¿Debería ser numérico o categórico?
3. ¿Qué columnas tienen más missings? ¿A qué sección del formulario corresponden?