In [1]:
import polars as pl

In [16]:
x= pl.DataFrame({
    "a":["a","b","c"],
    "b":["t","u","v"],
    "c":["1","2","3"],
        })

y= pl.DataFrame({
    "a":["a","b","d"],
    "b":["t","u","w"],
    "c":["4","5","6"],
        })

pl.concat([x,y], how='vertical')

shape: (6, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str │
╞═════╪═════╪═════╡
│ a   ┆ t   ┆ 1   │
│ b   ┆ u   ┆ 2   │
│ c   ┆ v   ┆ 3   │
│ a   ┆ t   ┆ 4   │
│ b   ┆ u   ┆ 5   │
│ d   ┆ w   ┆ 6   │
└─────┴─────┴─────┘

In [17]:
x= pl.DataFrame({
    "a":["a","b","c"],
    "b":["t","u","v"],
    "c":["1","2","3"],
        })

y= pl.DataFrame({
    "d":["a","b","d"],
    "e":["t","u","w"],
    "f":["4","5","6"],
        })

pl.concat([x,y], how='horizontal')

shape: (3, 6)
┌─────┬─────┬─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   ┆ e   ┆ f   │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ str ┆ str ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╡
│ a   ┆ t   ┆ 1   ┆ a   ┆ t   ┆ 4   │
│ b   ┆ u   ┆ 2   ┆ b   ┆ u   ┆ 5   │
│ c   ┆ v   ┆ 3   ┆ d   ┆ w   ┆ 6   │
└─────┴─────┴─────┴─────┴─────┴─────┘

In [ ]:
x= pl.DataFrame({
    "a":["a","b","c"],
    "b":["t","u","v"],
    "c":["1","2","3"],
        })

y= pl.DataFrame({
    "a":["a","b","d"],
    "b":["t","u","w"],
    "d":["3","2","1"],
        })

In [4]:
x.join(y,on="a",suffix='_r',how="left")

shape: (3, 5)
┌─────┬─────┬─────┬──────┬──────┐
│ a   ┆ b   ┆ c   ┆ b_r  ┆ d    │
│ --- ┆ --- ┆ --- ┆ ---  ┆ ---  │
│ str ┆ str ┆ str ┆ str  ┆ str  │
╞═════╪═════╪═════╪══════╪══════╡
│ a   ┆ t   ┆ 1   ┆ t    ┆ 3    │
│ b   ┆ u   ┆ 2   ┆ u    ┆ 2    │
│ c   ┆ v   ┆ 3   ┆ null ┆ null │
└─────┴─────┴─────┴──────┴──────┘

In [6]:
x.join(y,on="a",suffix='_r',how="inner")

shape: (2, 5)
┌─────┬─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ b_r ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ str ┆ str │
╞═════╪═════╪═════╪═════╪═════╡
│ a   ┆ t   ┆ 1   ┆ t   ┆ 3   │
│ b   ┆ u   ┆ 2   ┆ u   ┆ 2   │
└─────┴─────┴─────┴─────┴─────┘

In [ ]:
x.join(y,on="a",suffix='_r',how="full").sort("a")

shape: (4, 6)
┌──────┬──────┬──────┬──────┬──────┬──────┐
│ a    ┆ b    ┆ c    ┆ a_r  ┆ b_r  ┆ d    │
│ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str  ┆ str  ┆ str  ┆ str  ┆ str  ┆ str  │
╞══════╪══════╪══════╪══════╪══════╪══════╡
│ null ┆ null ┆ null ┆ d    ┆ w    ┆ 1    │
│ a    ┆ t    ┆ 1    ┆ a    ┆ t    ┆ 3    │
│ b    ┆ u    ┆ 2    ┆ b    ┆ u    ┆ 2    │
│ c    ┆ v    ┆ 3    ┆ null ┆ null ┆ null │
└──────┴──────┴──────┴──────┴──────┴──────┘

In [9]:
x.join(y,on="a",suffix='_r',how="semi")

shape: (2, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str │
╞═════╪═════╪═════╡
│ a   ┆ t   ┆ 1   │
│ b   ┆ u   ┆ 2   │
└─────┴─────┴─────┘

In [10]:
x.join(y,on="a",suffix='_r',how="anti")

shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ str ┆ str ┆ str │
╞═════╪═════╪═════╡
│ c   ┆ v   ┆ 3   │
└─────┴─────┴─────┘